import { createElement } from "react";
import dynamic from "next/dynamic";
import type { ComponentType } from "react";

const PasswordGenerator = dynamic(() => import("@/components/tools/PasswordGenerator"));
const ImageConverter = dynamic(() => import("@/components/tools/ImageConverter"));
const WhatsAppGenerator = dynamic(() => import("@/components/tools/WhatsAppGenerator"));
const QrCodeGenerator = dynamic(() => import("@/components/tools/QrCodeGeneratorCDN"));

import * as P1 from "@/components/tools/tools-part1";
import * as P2 from "@/components/tools/tools-part2";
import * as P3 from "@/components/tools/tools-part3";
import * as P4 from "@/components/tools/tools-part4";
import * as P5 from "@/components/tools/tools-part5";
import * as P6 from "@/components/tools/tools-part6";
const GifMaker = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.GifMaker));
const ExifViewer = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.ExifViewer));
const ImageMetadataEditor = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.ImageMetadataEditor));
const PdfToWord = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.PdfToWord));
const SmartImageLab = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.SmartImageLab));
const SmartVideoGenerator = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.SmartVideoGenerator));
const VoiceStyleStudio = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.VoiceStyleStudio));
const SmartAudioStudio = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.SmartAudioStudio));
const LipSyncStudio = dynamic(() => import("@/components/tools/tools-part7").then((module) => module.LipSyncStudio));

const wrap = (Comp: ComponentType<any>, props: Record<string, any> = {}) => {
  const C = () => createElement(Comp, props);
  C.displayName = "Wrapped";
  return C;
};

export const IMPLEMENTED_TOOLS: Record<string, ComponentType> = {
  "tiktok-ig-reels-downloader": wrap(P6.SocialMediaAssistant, { platform: "TikTok / Instagram" }),
  "youtube-shorts-downloader": wrap(P6.SocialMediaAssistant, { platform: "YouTube Shorts" }),
  "password-generator": PasswordGenerator,
  "image-converter": ImageConverter,
  "whatsapp-dm-generator": WhatsAppGenerator,
  "qr-code-generator": QrCodeGenerator,
  "word-counter": P1.WordCounter,
  "case-converter": P1.CaseConverter,
  "find-and-replace": P1.FindAndReplace,
  "remove-duplicate-lines": P1.RemoveDuplicateLines,
  "sort-lines": P1.SortLines,
  "trim-whitespace": P1.TrimWhitespace,
  "remove-line-breaks": P1.RemoveLineBreaks,
  "extract-emails-urls": P1.ExtractEmailsUrls,
  "notepad": P1.Notepad,
  "json-formatter": P1.JsonFormatter,
  "json-validator": P1.JsonValidator,
  "json-to-csv": P1.JsonToCsv,
  "csv-to-json": P1.CsvToJson,
  "json-minifier": P1.JsonFormatter,
  "base64-encode-decode": P1.Base64EncodeDecode,
  "url-encode-decode": P1.UrlEncodeDecode,
  "html-entity-encoder": P1.HtmlEntityEncoder,
  "text-encoder-decoder": P1.TextEncoderDecoder,
  "css-minifier": wrap(P1.Minifier, { lang: "css", mode: "minify" }),
  "js-minifier": wrap(P1.Minifier, { lang: "js", mode: "minify" }),
  "js-beautifier": wrap(P1.Minifier, { lang: "js", mode: "beautify" }),
  "html-formatter": wrap(P1.Minifier, { lang: "html", mode: "beautify" }),
  "css-beautifier": wrap(P1.Minifier, { lang: "css", mode: "beautify" }),
  "regex-tester": P1.RegexTester,
  "uuid-generator": P1.UuidGenerator,
  "hash-generator": P1.HashGenerator,
  "jwt-decoder": P1.JwtDecoder,
  "token-counter": P1.TokenCounter,
  "cron-builder": P1.CronBuilder,
  "color-converter": P1.ColorConverter,
  "text-reverser": P2.TextReverser,
  "lorem-ipsum": P2.LoremIpsum,
  "random-text": P2.RandomText,
  "url-slug-generator": P2.UrlSlugGenerator,
  "number-formatter": P2.NumberFormatter,
  "base-converter": P2.BaseConverter,
  "unit-converter": P2.UnitConverter,
  "timezone-converter": P2.TimezoneConverter,
  "currency-converter": P2.CurrencyConverter,
  "percentage-calculator": P2.PercentageCalculator,
  "bmi-calculator": P2.BmiCalculator,
  "age-calculator": P2.AgeCalculator,
  "date-difference": P2.DateDifference,
  "compound-interest": P2.CompoundInterest,
  "loan-calculator": P2.LoanCalculator,
  "mortgage-calculator": wrap(P2.LoanCalculator, { labelPrincipal: "Home price", defaultYears: 30 }),
  "car-loan-calculator": wrap(P2.LoanCalculator, { labelPrincipal: "Car price", defaultYears: 5 }),
  "tip-calculator": P2.TipCalculator,
  "discount-calculator": P2.DiscountCalculator,
  "sales-tax": P2.SalesTax,
  "bill-splitter": P2.BillSplitter,
  "gpa-calculator": P2.GpaCalculator,
  "inflation-calculator": P2.InflationCalculator,
  "gas-cost-calculator": P2.GasCostCalculator,
  "random-number": P2.RandomNumber,
  "countdown-timer": P2.CountdownTimer,
  "stopwatch": P2.Stopwatch,
  "fake-data-generator": P2.FakeDataGenerator,
  "net-worth": P2.NetWorth,
  "savings-goal": P2.SavingsGoal,
  "debt-payoff": P2.DebtPayoff,
  "credit-card-payoff": wrap(P2.DebtPayoff, { label: "Card balance" }),
  "paye-tax": wrap(P2.PayeTax, { label: "Gross annual income" }),
  "paycheck-calculator": P2.PayeTax,
  "barcode-generator": P2.BarcodeGenerator,
  "username-generator": P3.UsernameGenerator,
  "business-name-generator": P3.BusinessNameGenerator,
  "random-name-picker": P3.RandomNamePicker,
  "coin-flip": P3.CoinFlip,
  "spin-wheel": P3.SpinWheel,
  "to-do-list": P3.ToDoList,
  "habit-tracker": P3.HabitTracker,
  "typing-test": P3.TypingTest,
  "emoji-picker": P3.EmojiPicker,
  "fancy-text": P3.FancyText,
  "image-compressor": P3.ImageCompressor,
  "image-resizer": P3.ImageResizer,
  "image-rotator": P3.ImageRotator,
  "image-flip": P3.ImageFlip,
  "image-grayscale": P3.ImageGrayscale,
  "image-round-corners": P3.ImageRoundCorners,
  "image-to-base64": P3.ImageToBase64,
  "base64-to-image": P6.Base64ToImage,
  "image-collage": wrap(P6.ImageGridTool, { mode: "collage" }),
  "gif-maker": GifMaker,
  "image-combiner": wrap(P6.ImageGridTool, { mode: "combine" }),
  "image-splitter": wrap(P6.ImageGridTool, { mode: "split" }),
  "webp-converter": ImageConverter,
  "exif-remover": ImageConverter,
  "exif-viewer": ExifViewer,
  "image-metadata-editor": ImageMetadataEditor,
  "color-picker-from-image": P3.ColorPickerFromImage,
  "png-to-jpg": P3.PngToJpg,
  "image-watermark": P3.ImageWatermark,
  "image-text-overlay": P3.ImageWatermark,
  "meta-og-generator": P3.MetaOgGenerator,
  "robots-txt-generator": P3.RobotsTxtGenerator,
  "sitemap-generator": P3.SitemapGenerator,
  "keyword-density": P3.KeywordDensity,
  "image-cropper": P4.ImageCropper,
  "photo-filters": P4.PhotoFilters,
  "meme-generator": P4.MemeGenerator,
  "svg-to-png": P4.SvgToPng,
  "screen-recorder": P4.ScreenRecorder,
  "frame-grabber": P4.FrameGrabber,
  "video-thumbnail": P4.FrameGrabber,
  "image-background-color": P4.ImageBackgroundColor,
  "css-gradient": P4.CssGradientGenerator,
  "css-shadow": P4.CssShadowGenerator,
  "glassmorphism": P4.GlassmorphismGenerator,
  "json-to-typescript": P4.JsonToTypescript,
  "money-manager": P4.MoneyManager,
  "rent-vs-buy": P4.RentVsBuy,
  "grade-calculator": P4.GradeCalculator,
  "invoice-generator": P4.InvoiceGenerator,
  "handwriting-text": P4.HandwritingText,
  "pdf-merge": P5.PdfMerge,
  "pdf-split": P5.PdfSplit,
  "pdf-watermark": P5.PdfWatermark,
  "pdf-extract-text": P5.PdfExtractText,
  "markdown-to-html": P5.MarkdownToHtml,
  "text-diff": P5.TextDiff,
  "diff-checker": P5.TextDiff,
  "curl-to-code": P6.CurlToCode,
  "json-to-zod": P6.JsonToZod,
  "jsonl-viewer": P6.JsonLinesViewer,
  "json-schema-builder": P6.JsonSchemaBuilder,
  "chat-export-converter": P6.DataConverter,
  "social-preview-checker": P6.SocialPreviewChecker,
  "heic-to-jpg": P5.HeicToJpg,
  "audio-converter": P5.AudioConverter,
  "audio-trimmer": P5.AudioTrimmer,
  "audio-reverse": P5.AudioReverse,
  "gif-to-video": wrap(P5.FFmpegTool, { inputAccept: "image/gif", outputExt: "mp4", outputMime: "video/mp4", outputName: "animation.mp4", ffmpegLabel: "Convert GIF to MP4", ffmpegArgs: (i: string, o: string) => ["-i", i, "-movflags", "faststart", "-pix_fmt", "yuv420p", o] }),
  "video-trimmer": wrap(P5.FFmpegTool, { inputAccept: "video/*", outputExt: "mp4", outputMime: "video/mp4", outputName: "trimmed.mp4", ffmpegLabel: "Trim first 30 seconds", ffmpegArgs: (i: string, o: string) => ["-i", i, "-t", "30", "-c:v", "libx264", "-c:a", "aac", o] }),
  "video-resizer": wrap(P5.FFmpegTool, { inputAccept: "video/*", outputExt: "mp4", outputMime: "video/mp4", outputName: "resized.mp4", ffmpegLabel: "Resize to 1280px", ffmpegArgs: (i: string, o: string) => ["-i", i, "-vf", "scale=1280:-2", "-c:a", "copy", o] }),
  "video-speed": wrap(P5.FFmpegTool, { inputAccept: "video/*", outputExt: "mp4", outputMime: "video/mp4", outputName: "speed-2x.mp4", ffmpegLabel: "Create 2× version", ffmpegArgs: (i: string, o: string) => ["-i", i, "-filter_complex", "[0:v]setpts=0.5*PTS[v];[0:a]atempo=2.0[a]", "-map", "[v]", "-map", "[a]", o] }),
  "audio-compressor": wrap(P5.FFmpegTool, { inputAccept: "audio/*", outputExt: "mp3", outputMime: "audio/mpeg", outputName: "compressed.mp3", ffmpegLabel: "Compress audio", ffmpegArgs: (i: string, o: string) => ["-i", i, "-codec:a", "libmp3lame", "-b:a", "96k", o] }),
  "audio-volume-booster": wrap(P5.FFmpegTool, { inputAccept: "audio/*", outputExt: "mp3", outputMime: "audio/mpeg", outputName: "boosted.mp3", ffmpegLabel: "Boost volume 2×", ffmpegArgs: (i: string, o: string) => ["-i", i, "-af", "volume=2", "-codec:a", "libmp3lame", o] }),
  "audio-normalizer": wrap(P5.FFmpegTool, { inputAccept: "audio/*", outputExt: "mp3", outputMime: "audio/mpeg", outputName: "normalized.mp3", ffmpegLabel: "Normalize loudness", ffmpegArgs: (i: string, o: string) => ["-i", i, "-af", "loudnorm", "-codec:a", "libmp3lame", o] }),
  "video-converter": P5.VideoConverter,
  "video-compressor": P5.VideoCompressor,
  "video-mute": P5.VideoMute,
  "video-to-audio": P5.VideoToAudio,
  "video-to-gif": P5.VideoToGif,
  "ai-text-rewriter": P5.AiTextRewriter,
  "ai-paraphraser": P5.AiParaphraser,
  "ai-grammar-checker": P5.AiGrammarChecker,
  "ai-email-writer": P5.AiEmailWriter,
  "ai-headline-generator": P5.AiHeadlineGenerator,
  "ai-translator": P5.AiTranslator,
  "pdf-compress": wrap(P6.PdfWorkshop, { mode: "compress" }),
  "pdf-sign": wrap(P6.PdfWorkshop, { mode: "sign" }),
  "pdf-form-filler": wrap(P6.PdfWorkshop, { mode: "form" }),
  "pdf-unlock": wrap(P6.PdfWorkshop, { mode: "unlock" }),
  "pdf-header-footer": wrap(P6.PdfWorkshop, { mode: "header-footer" }),
  "pdf-resize": wrap(P6.PdfWorkshop, { mode: "resize" }),
  "pdf-to-word": PdfToWord,
  "word-to-pdf": P6.TextToPdf,
  "cv-builder": wrap(P6.TextToPdf, { cv: true }),
  "csv-json-converter": P1.CsvToJson,
  "bookkeeping": P4.MoneyManager,
  "qr-code-scanner": P6.QrScanner,
  "ai-blog-writer": wrap(P5.AITextWriter, { task: "Write a well-structured, useful blog post from this brief. Include a title and headings.", placeholder: "Topic, audience, tone, and key points…", label: "Write blog post" }),
  "ai-caption-generator": wrap(P5.AITextWriter, { task: "Create 8 engaging social captions in varied tones, with restrained relevant hashtags.", placeholder: "Describe the post…", label: "Generate captions" }),
  "ai-resume-writer": wrap(P5.AITextWriter, { task: "Turn these career notes into concise, achievement-focused resume content. Never invent facts.", placeholder: "Role, experience, outcomes, and skills…", label: "Draft resume" }),
  "ai-product-description": wrap(P5.AITextWriter, { task: "Write a clear, persuasive product description using only the supplied facts.", placeholder: "Product facts and audience…", label: "Write description" }),
  "ai-tweet-generator": wrap(P5.AITextWriter, { task: "Write 5 concise social posts under 280 characters. Avoid clickbait.", placeholder: "Topic and voice…", label: "Generate posts" }),
  "ai-image-generator": wrap(P6.AiImageStudio, { style: "cinematic editorial" }),
  "ai-background-remover": wrap(SmartImageLab, { mode: "background" }),
  "ai-image-enhancer": wrap(SmartImageLab, { mode: "enhance" }),
  "ai-retouch": wrap(SmartImageLab, { mode: "retouch" }),
  "ai-colorize": wrap(SmartImageLab, { mode: "colorize" }),
  "ai-object-remover": wrap(SmartImageLab, { mode: "remove" }),
  "ai-logo-generator": wrap(P6.AiImageStudio, { style: "minimal vector logo on a plain background" }),
  "ai-thumbnail-generator": wrap(P6.AiImageStudio, { style: "high-impact video thumbnail with clear visual hierarchy" }),
  "ai-sketch-to-image": wrap(P6.AiImageStudio, { style: "concept art derived from a sketch description" }),
  "ai-profile-pic": wrap(P6.AiImageStudio, { style: "professional profile portrait" }),
  "ai-video-generator": SmartVideoGenerator,
  "ai-subtitle-generator": wrap(P5.AITextWriter, { task: "Convert this transcript into concise SRT subtitles with sensible timing placeholders.", placeholder: "Paste a transcript…", label: "Create subtitles" }),
  "ai-voice-generator": P6.VoiceGenerator,
  "ai-voice-clone": VoiceStyleStudio,
  "ai-noise-removal": SmartAudioStudio,
  "ai-podcast-editor": wrap(SmartAudioStudio, { podcast: true }),
  "ai-speech-to-text": P6.SpeechToText,
  "ai-video-summarizer": wrap(P5.AITextWriter, { task: "Summarize this video transcript into key points, decisions, and action items.", placeholder: "Paste a transcript…", label: "Summarize" }),
  "ai-code-generator": wrap(P5.AITextWriter, { task: "Generate clean, secure code for this request. State the language and important assumptions.", placeholder: "Describe what to build…", label: "Generate code" }),
  "ai-debugger": wrap(P5.AITextWriter, { task: "Diagnose this code and error. Explain the root cause, then provide a minimal corrected version.", placeholder: "Paste code and the exact error…", label: "Debug" }),
  "ai-regex-generator": wrap(P5.AITextWriter, { task: "Generate a safe regular expression for this requirement, with test examples and flags.", placeholder: "Describe what should match…", label: "Generate regex" }),
  "ai-sql-generator": wrap(P5.AITextWriter, { task: "Generate parameterized SQL for this requirement. Explain the expected schema assumptions.", placeholder: "Describe the query and tables…", label: "Generate SQL" }),
  "ai-json-fixer": wrap(P5.AITextWriter, { task: "Repair this malformed JSON. Return only valid JSON without markdown fences.", placeholder: "Paste malformed JSON…", label: "Fix JSON" }),
  "ai-mock-api": wrap(P5.AITextWriter, { task: "Design a concise mock REST API: resources, routes, example requests, and JSON responses.", placeholder: "Describe the product domain…", label: "Design mock API" }),
  "ai-chatbot-builder": wrap(P5.AITextWriter, { task: "Create a production-ready chatbot system prompt with role, boundaries, workflow, and fallback behavior.", placeholder: "Describe the chatbot…", label: "Build prompt" }),
  "ai-prompt-generator": wrap(P5.AITextWriter, { task: "Transform this goal into a precise reusable AI prompt with context, constraints, and output format.", placeholder: "What should the AI accomplish?", label: "Generate prompt" }),
  "ai-document-summarizer": wrap(P5.AITextWriter, { task: "Summarize this document faithfully. Separate main points, evidence, risks, and actions.", placeholder: "Paste document text…", label: "Summarize document" }),
  "ai-pdf-chat": wrap(P5.AITextWriter, { task: "Answer the question using only the pasted PDF text. If unsupported, say so clearly.", placeholder: "Paste PDF text, then your question…", label: "Ask document" }),
  "ai-lip-sync": LipSyncStudio,
};

export const SOCIAL_DOWNLOADERS: Record<string, string> = {
  "tiktok-ig-reels-downloader": "TikTok / Instagram",
  "youtube-shorts-downloader": "YouTube Shorts",
};
export const IMPLEMENTED_SLUGS = new Set(Object.keys(IMPLEMENTED_TOOLS));
