"use client";
/* eslint-disable @next/next/no-img-element, react-hooks/exhaustive-deps -- local blob previews and timer lifecycle */
import { useEffect, useMemo, useRef, useState } from "react";
import { Plus, RefreshCw, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { CopyButton, OutputField } from "@/components/tools/_shared";
import { cn } from "@/lib/utils";
import * as U from "@/lib/tools-utils";

// ════════════════════════════ CONVERTERS ════════════════════════════
export function TextReverser() {
  const [text, setText] = useState(""); const [mode, setMode] = useState<"chars"|"words"|"lines">("chars");
  return (<div className="space-y-4"><Textarea rows={5} value={text} onChange={(e)=>setText(e.target.value)} placeholder="Text…" /><div className="flex gap-2">{(["chars","words","lines"] as const).map(m => <button key={m} type="button" onClick={()=>setMode(m)} aria-pressed={mode===m} className={cn("rounded-md border px-3 py-1.5 text-xs capitalize", mode===m?"border-transparent bg-gradient-accent text-white":"border-border text-muted-foreground hover:text-foreground")}>Reverse {m}</button>)}</div><OutputField value={text ? U.reverseText(text, mode) : ""} /></div>);
}
export function LoremIpsum() {
  const [count, setCount] = useState(3); const [out, setOut] = useState("");
  return (<div className="space-y-4"><div className="flex items-center gap-3"><label className="text-sm text-muted-foreground">Paragraphs</label><input type="number" min={1} max={20} value={count} onChange={(e)=>setCount(Math.min(20,Math.max(1,+e.target.value)))} className="h-9 w-20 rounded-md border border-border bg-card/50 px-2 text-sm" /><Button variant="gradient" onClick={()=>setOut(U.loremIpsum(count))}>Generate</Button></div><OutputField value={out} rows={10} mono={false} /></div>);
}
export function RandomText() {
  const [text, setText] = useState(""); const [count, setCount] = useState(5); const [sep, setSep] = useState<"newline"|"space"|"none">("newline");
  return (<div className="space-y-4"><div className="space-y-1.5"><Label>Text to repeat</Label><Textarea rows={3} value={text} onChange={(e)=>setText(e.target.value)} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Count</Label><Input type="number" min={1} max={1000} value={count} onChange={(e)=>setCount(Math.min(1000,Math.max(1,+e.target.value)))} /></div><div className="space-y-1.5"><Label>Separator</Label><select value={sep} onChange={(e)=>setSep(e.target.value as any)} className="h-10 w-full rounded-md border border-border bg-card/50 px-2 text-sm"><option value="newline">New line</option><option value="space">Space</option><option value="none">None</option></select></div></div><OutputField value={text ? U.repeatText(text, count, sep) : ""} rows={6} /></div>);
}
export function UrlSlugGenerator() {
  const [text, setText] = useState(""); const [sep, setSep] = useState("-");
  return (<div className="space-y-4"><div className="space-y-1.5"><Label>Title or text</Label><Input value={text} onChange={(e)=>setText(e.target.value)} placeholder="My Awesome Post!" /></div><div className="space-y-1.5 max-w-[10rem]"><Label>Separator</Label><Input value={sep} onChange={(e)=>setSep(e.target.value||"-")} maxLength={1} /></div><OutputField value={text ? U.slugify(text, sep) : ""} /></div>);
}
export function NumberFormatter() {
  const [num, setNum] = useState("1234567.89"); const [decimals, setDecimals] = useState(2);
  const n = parseFloat(num); const fmt = (locale: string) => isNaN(n) ? "" : n.toLocaleString(locale, {minimumFractionDigits: decimals, maximumFractionDigits: decimals});
  const outs: [string,string][] = [["US", fmt("en-US")],["UK", fmt("en-GB")],["German", fmt("de-DE")],["Indian", fmt("en-IN")]];
  return (<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Number</Label><Input value={num} onChange={(e)=>setNum(e.target.value)} className="font-mono" /></div><div className="space-y-1.5"><Label>Decimals</Label><Input type="number" min={0} max={10} value={decimals} onChange={(e)=>setDecimals(Math.min(10,Math.max(0,+e.target.value)))} /></div></div><div className="space-y-2">{outs.map(([l,v]) => <div key={l} className="flex items-center justify-between rounded-md border border-border bg-background/50 px-3 py-2"><div><span className="text-xs text-muted-foreground">{l}</span><p className="font-mono text-lg">{v}</p></div><CopyButton value={v} /></div>)}</div></div>);
}
export function BaseConverter() {
  const [value, setValue] = useState("255"); const [from, setFrom] = useState(10);
  const BASES = [{id:2,label:"Binary"},{id:8,label:"Octal"},{id:10,label:"Decimal"},{id:16,label:"Hex"}];
  return (<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Value</Label><Input value={value} onChange={(e)=>setValue(e.target.value)} className="font-mono" /></div><div className="space-y-1.5"><Label>From base</Label><div className="flex gap-2">{BASES.map(b=><button key={b.id} type="button" onClick={()=>setFrom(b.id)} aria-pressed={from===b.id} className={`flex-1 rounded-md border px-2 py-2 text-xs ${from===b.id?"border-transparent bg-gradient-accent text-white":"border-border text-muted-foreground"}`}>{b.label}</button>)}</div></div></div><div className="grid gap-3 sm:grid-cols-2">{BASES.filter(b=>b.id!==from).map(b => <div key={b.id} className="rounded-md border border-border bg-background/50 px-3 py-2"><span className="text-xs text-muted-foreground">{b.label} (base {b.id})</span><p className="mt-0.5 break-all font-mono text-lg">{U.baseConvert(value, from, b.id)}</p></div>)}</div></div>);
}
const UNIT_CATS: Record<string, {units: [string, number][]}> = { Length: {units:[["km",1000],["m",1],["cm",0.01],["mm",0.001],["mi",1609.344],["ft",0.3048],["in",0.0254]]}, Weight: {units:[["kg",1],["g",0.001],["lb",0.45359237],["oz",0.028349523]]}, Volume: {units:[["l",1],["ml",0.001],["gal",3.785411784],["cup",0.2365882365]]}, Speed: {units:[["km/h",0.277778],["mph",0.44704],["m/s",1],["knot",0.514444]]} };
export function UnitConverter() {
  const [cat, setCat] = useState("Length"); const [val, setVal] = useState("1"); const [from, setFrom] = useState("m"); const [to, setTo] = useState("ft");
  const def = UNIT_CATS[cat]; const ff = def.units.find(u=>u[0]===from)?.[1] ?? 1; const tf = def.units.find(u=>u[0]===to)?.[1] ?? 1;
  const result = (parseFloat(val) * ff) / tf;
  return (<div className="space-y-4"><div className="flex flex-wrap gap-2">{Object.keys(UNIT_CATS).map(c=><button key={c} type="button" onClick={()=>{setCat(c);setFrom(UNIT_CATS[c].units[0][0]);setTo(UNIT_CATS[c].units[1][0]);}} aria-pressed={cat===c} className={`rounded-md border px-3 py-1.5 text-xs ${cat===c?"border-transparent bg-gradient-accent text-white":"border-border text-muted-foreground hover:text-foreground"}`}>{c}</button>)}</div><div className="grid items-end gap-3 sm:grid-cols-[1fr_auto_1fr]"><div className="space-y-1.5"><Label>From</Label><Input type="number" value={val} onChange={(e)=>setVal(e.target.value)} /><select value={from} onChange={(e)=>setFrom(e.target.value)} className="h-10 w-full rounded-md border border-border bg-card/50 px-2 text-sm">{def.units.map(u=><option key={u[0]} value={u[0]}>{u[0]}</option>)}</select></div><button type="button" onClick={()=>{setFrom(to);setTo(from);}} className="mb-1 size-10 self-end rounded-md border border-border text-muted-foreground hover:text-accent">⇄</button><div className="space-y-1.5"><Label>To</Label><Input readOnly value={isFinite(result)?result.toLocaleString(undefined,{maximumFractionDigits:6}):""} className="font-mono" /><select value={to} onChange={(e)=>setTo(e.target.value)} className="h-10 w-full rounded-md border border-border bg-card/50 px-2 text-sm">{def.units.map(u=><option key={u[0]} value={u[0]}>{u[0]}</option>)}</select></div></div></div>);
}
const ZONES = ["UTC","America/New_York","America/Los_Angeles","Europe/London","Europe/Paris","Asia/Dubai","Asia/Karachi","Asia/Kolkata","Asia/Colombo","Asia/Tokyo","Australia/Sydney"];
export function TimezoneConverter() {
  const [datetime, setDatetime] = useState(() => { const d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16); }); const [to, setTo] = useState("Asia/Colombo");
  let result = ""; try { result = new Intl.DateTimeFormat("en-US",{timeZone:to,dateStyle:"full",timeStyle:"long"}).format(new Date(datetime)); } catch {}
  return (<div className="space-y-4"><div className="space-y-1.5"><Label>Date & time</Label><Input type="datetime-local" value={datetime} onChange={(e)=>setDatetime(e.target.value)} /></div><div className="space-y-1.5"><Label>To zone</Label><select value={to} onChange={(e)=>setTo(e.target.value)} className="h-10 w-full rounded-md border border-border bg-card/50 px-2 text-sm">{ZONES.map(z=><option key={z}>{z}</option>)}</select></div><div className="glass rounded-lg p-4 text-center"><div className="text-sm font-medium text-gradient-accent">{result}</div></div></div>);
}
const RATES: Record<string, number> = { USD:1, EUR:0.92, GBP:0.79, JPY:155, AUD:1.51, CAD:1.36, CNY:7.24, INR:83.5, LKR:300, PKR:278, AED:3.67, SGD:1.35 };
export function CurrencyConverter() {
  const [amount, setAmount] = useState("100"); const [from, setFrom] = useState("USD"); const [to, setTo] = useState("LKR");
  const CODES = Object.keys(RATES); const a = parseFloat(amount); const result = (a / RATES[from]) * RATES[to];
  return (<div className="space-y-4"><div className="grid items-end gap-3 sm:grid-cols-[1fr_auto_1fr]"><div className="space-y-1.5"><Label>Amount</Label><Input type="number" value={amount} onChange={(e)=>setAmount(e.target.value)} /><select value={from} onChange={(e)=>setFrom(e.target.value)} className="h-10 w-full rounded-md border border-border bg-card/50 px-2 text-sm">{CODES.map(c=><option key={c}>{c}</option>)}</select></div><button type="button" onClick={()=>{setFrom(to);setTo(from);}} className="mb-1 size-10 self-end rounded-md border border-border text-muted-foreground hover:text-accent">⇄</button><div className="space-y-1.5"><Label>Converted</Label><Input readOnly value={isFinite(result)?result.toLocaleString(undefined,{maximumFractionDigits:2}):""} className="font-mono" /><select value={to} onChange={(e)=>setTo(e.target.value)} className="h-10 w-full rounded-md border border-border bg-card/50 px-2 text-sm">{CODES.map(c=><option key={c}>{c}</option>)}</select></div></div><p className="text-xs text-muted-foreground">⚠ Indicative static rates — not live.</p></div>);
}

// ════════════════════════════ CALCULATORS / FINANCE ════════════════════════════
const money = (n:number)=>n.toLocaleString(undefined,{style:"currency",currency:"USD"});
export function PercentageCalculator() {
  const [a, setA] = useState("25"); const [b, setB] = useState("200"); const x = parseFloat(a), y = parseFloat(b); const f = (n:number)=>isNaN(n)?"—":(Math.round(n*10000)/10000).toString();
  const rows: [string,string][] = [[`${a}% of ${b}`, f((x/100)*y)],[`${a} is what % of ${b}`, y?f((x/y)*100)+"%":"—"],[`% change ${a}→${b}`, x?f(((y-x)/x)*100)+"%":"—"]];
  return (<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Value A</Label><Input type="number" value={a} onChange={(e)=>setA(e.target.value)} /></div><div className="space-y-1.5"><Label>Value B</Label><Input type="number" value={b} onChange={(e)=>setB(e.target.value)} /></div></div><div className="space-y-2">{rows.map(([l,v]) => <div key={l} className="flex items-center justify-between rounded-md border border-border bg-background/50 px-3 py-2"><span className="text-sm text-muted-foreground">{l}</span><span className="font-mono text-lg text-accent">{v}</span></div>)}</div></div>);
}
export function BmiCalculator() {
  const [height, setHeight] = useState("175"); const [weight, setWeight] = useState("70"); const [unit, setUnit] = useState<"metric"|"imperial">("metric");
  const h = parseFloat(height), w = parseFloat(weight); let bmi = unit==="metric" ? (h>0?w/((h/100)*(h/100)):0) : (h>0?(w/(h*h))*703:0);
  const cat = bmi<18.5?"Underweight":bmi<25?"Normal":bmi<30?"Overweight":"Obese"; const color = bmi<18.5?"text-blue-400":bmi<25?"text-emerald-400":bmi<30?"text-amber-400":"text-red-400";
  return (<div className="space-y-4"><div className="flex gap-2">{(["metric","imperial"] as const).map(u=><button key={u} type="button" onClick={()=>setUnit(u)} aria-pressed={unit===u} className={`flex-1 rounded-md border px-3 py-2 text-sm capitalize ${unit===u?"border-transparent bg-gradient-accent text-white":"border-border text-muted-foreground"}`}>{u}</button>)}</div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Height ({unit==="metric"?"cm":"in"})</Label><Input type="number" value={height} onChange={(e)=>setHeight(e.target.value)} /></div><div className="space-y-1.5"><Label>Weight ({unit==="metric"?"kg":"lb"})</Label><Input type="number" value={weight} onChange={(e)=>setWeight(e.target.value)} /></div></div><div className="glass rounded-lg p-5 text-center"><div className="text-4xl font-bold text-gradient-accent">{bmi?bmi.toFixed(1):"—"}</div><div className={`mt-1 text-sm font-medium ${color}`}>{bmi>0?cat:"Enter details"}</div></div></div>);
}
export function AgeCalculator() {
  const [dob, setDob] = useState(""); let result = "";
  if (dob) { const b=new Date(dob), now=new Date(); if(!isNaN(b.getTime())&&b<=now){ let y=now.getFullYear()-b.getFullYear(), m=now.getMonth()-b.getMonth(), d=now.getDate()-b.getDate(); if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate();} if(m<0){y--;m+=12;} result=`${y}y ${m}m ${d}d (${Math.floor((now.getTime()-b.getTime())/86400000).toLocaleString()} days total)`; } }
  return (<div className="space-y-4"><div className="space-y-1.5 max-w-xs"><Label>Date of birth</Label><Input type="date" value={dob} onChange={(e)=>setDob(e.target.value)} /></div><div className="glass rounded-lg p-5 text-center"><div className="text-xl font-semibold text-gradient-accent">{result||"Pick your date of birth"}</div></div></div>);
}
export function DateDifference() {
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); let out = "";
  if(from&&to){const a=new Date(from),b=new Date(to);if(!isNaN(a.getTime())&&!isNaN(b.getTime())){const days=Math.floor(Math.abs(b.getTime()-a.getTime())/86400000);out=`${days.toLocaleString()} days · ${Math.floor(days/7).toLocaleString()} weeks · ${(days/30.44).toFixed(1)} months · ${(days/365.25).toFixed(2)} years`;}}
  return (<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>From</Label><Input type="date" value={from} onChange={(e)=>setFrom(e.target.value)} /></div><div className="space-y-1.5"><Label>To</Label><Input type="date" value={to} onChange={(e)=>setTo(e.target.value)} /></div></div><div className="glass rounded-lg p-5 text-center"><div className="text-lg font-semibold text-gradient-accent">{out||"Select both dates"}</div></div></div>);
}
export function CompoundInterest() {
  const [p, setP]=useState("10000"),[r,setR]=useState("7"),[y,setY]=useState("10"),[m,setM]=useState("100");
  const P=parseFloat(p),R=parseFloat(r)/100,Y=parseFloat(y),M=parseFloat(m);const mr=R/12,n=Y*12;let fv=P>0?P*Math.pow(1+mr,n):0;if(M>0&&mr>0)fv+=M*((Math.pow(1+mr,n)-1)/mr);else if(M>0)fv+=M*n;const contrib=P+M*n;
  return (<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Initial</Label><Input type="number" value={p} onChange={(e)=>setP(e.target.value)} /></div><div className="space-y-1.5"><Label>Rate %</Label><Input type="number" step="0.01" value={r} onChange={(e)=>setR(e.target.value)} /></div><div className="space-y-1.5"><Label>Years</Label><Input type="number" value={y} onChange={(e)=>setY(e.target.value)} /></div><div className="space-y-1.5"><Label>Monthly</Label><Input type="number" value={m} onChange={(e)=>setM(e.target.value)} /></div></div><div className="grid grid-cols-3 gap-3">{[["Future value",money(fv)],["Contributions",money(contrib)],["Interest",money(fv-contrib)]].map(([l,v])=><div key={l} className="glass rounded-lg p-3 text-center"><div className="text-base font-semibold text-gradient-accent">{v}</div><div className="text-xs text-muted-foreground">{l}</div></div>)}</div></div>);
}
function amortize(principal:number, ratePct:number, years:number){const r=ratePct/100/12,n=years*12;if(principal<=0||n<=0)return{monthly:0,total:0,interest:0};const monthly=r===0?principal/n:(principal*r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1);const total=monthly*n;return{monthly,total,interest:total-principal};}
export function LoanCalculator({labelPrincipal="Loan amount",defaultYears=30}:{labelPrincipal?:string;defaultYears?:number}){
  const [a,setA]=useState("250000"),[r,setR]=useState("5.5"),[y,setY]=useState(String(defaultYears));
  const {monthly,total,interest}=amortize(parseFloat(a),parseFloat(r),parseFloat(y));
  return (<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="space-y-1.5"><Label>{labelPrincipal}</Label><Input type="number" value={a} onChange={(e)=>setA(e.target.value)} /></div><div className="space-y-1.5"><Label>Rate %</Label><Input type="number" step="0.01" value={r} onChange={(e)=>setR(e.target.value)} /></div><div className="space-y-1.5"><Label>Years</Label><Input type="number" value={y} onChange={(e)=>setY(e.target.value)} /></div></div><div className="grid grid-cols-3 gap-3">{[["Monthly",money(monthly)],["Total",money(total)],["Interest",money(interest)]].map(([l,v])=><div key={l} className="glass rounded-lg p-3 text-center"><div className="text-base font-semibold text-gradient-accent">{v}</div><div className="text-xs text-muted-foreground">{l}</div></div>)}</div></div>);
}
export function TipCalculator(){const[b,setB]=useState("50"),[t,setT]=useState("15"),[p,setP]=useState("2");const bill=parseFloat(b),tip=parseFloat(t)/100,people=Math.max(1,parseInt(p)||1);const ta=bill*tip,tot=bill+ta;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="space-y-1.5"><Label>Bill</Label><Input type="number" value={b} onChange={(e)=>setB(e.target.value)} /></div><div className="space-y-1.5"><Label>Tip %</Label><Input type="number" value={t} onChange={(e)=>setT(e.target.value)} /></div><div className="space-y-1.5"><Label>People</Label><Input type="number" min={1} value={p} onChange={(e)=>setP(e.target.value)} /></div></div><div className="flex flex-wrap gap-2">{[10,15,18,20,25].map(v=><button key={v} type="button" onClick={()=>setT(String(v))} className={cn("rounded-md border px-3 py-1.5 text-xs",+t===v?"border-transparent bg-gradient-accent text-white":"border-border text-muted-foreground")}>{v}%</button>)}</div><div className="grid grid-cols-3 gap-3">{[["Tip",money(ta)],["Total",money(tot)],["Per person",money(tot/people)]].map(([l,v])=><div key={l} className="glass rounded-lg p-3 text-center"><div className="text-base font-semibold text-gradient-accent">{v}</div><div className="text-xs text-muted-foreground">{l}</div></div>)}</div></div>);}
export function DiscountCalculator(){const[p,setP]=useState("100"),[d,setD]=useState("25");const pr=parseFloat(p),dc=parseFloat(d)/100;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Price</Label><Input type="number" value={p} onChange={(e)=>setP(e.target.value)} /></div><div className="space-y-1.5"><Label>Discount %</Label><Input type="number" value={d} onChange={(e)=>setD(e.target.value)} /></div></div><div className="grid grid-cols-2 gap-3">{[["You save",money(pr*dc)],["Final",money(pr-pr*dc)]].map(([l,v])=><div key={l} className="glass rounded-lg p-4 text-center"><div className="text-xl font-semibold text-gradient-accent">{v}</div><div className="text-xs text-muted-foreground">{l}</div></div>)}</div></div>);}
export function SalesTax(){const[a,setA]=useState("100"),[r,setR]=useState("8");const am=parseFloat(a),ra=parseFloat(r)/100;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Amount</Label><Input type="number" value={a} onChange={(e)=>setA(e.target.value)} /></div><div className="space-y-1.5"><Label>Tax %</Label><Input type="number" step="0.01" value={r} onChange={(e)=>setR(e.target.value)} /></div></div><div className="space-y-2">{[["Tax",money(am*ra)],["+ tax",money(am+am*ra)],["− tax",money(am/(1+ra))]].map(([l,v])=><div key={l} className="flex items-center justify-between rounded-md border border-border bg-background/50 px-3 py-2"><span className="text-sm text-muted-foreground">{l}</span><span className="font-mono text-accent">{v}</span></div>)}</div></div>);}
export function BillSplitter(){const[t,setT]=useState("120"),[p,setP]=useState("4");const tot=parseFloat(t),people=Math.max(1,parseInt(p)||1);return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Bill</Label><Input type="number" value={t} onChange={(e)=>setT(e.target.value)} /></div><div className="space-y-1.5"><Label>People</Label><Input type="number" min={1} value={p} onChange={(e)=>setP(e.target.value)} /></div></div><div className="glass rounded-lg p-6 text-center"><div className="text-3xl font-bold text-gradient-accent">{money(tot/people)}</div><div className="text-sm text-muted-foreground">per person</div></div></div>);}
const GRADE_POINTS: Record<string,number> = {"A+":4.0,"A":4.0,"A-":3.7,"B+":3.3,"B":3.0,"B-":2.7,"C+":2.3,"C":2.0,"C-":1.7,"D":1.0,"F":0};
export function GpaCalculator(){const[courses,setCourses]=useState([{grade:"A",credits:"3"},{grade:"B+",credits:"4"}]);let pts=0,creds=0;for(const c of courses){const gp=GRADE_POINTS[c.grade.toUpperCase()]??0;const cr=parseFloat(c.credits)||0;pts+=gp*cr;creds+=cr;}const gpa=creds?pts/creds:0;function upd(i:number,f:"grade"|"credits",v:string){setCourses(c=>c.map((x,idx)=>idx===i?{...x,[f]:v}:x));}return(<div className="space-y-4"><div className="space-y-2">{courses.map((c,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2"><select value={c.grade} onChange={(e)=>upd(i,"grade",e.target.value)} className="h-10 rounded-md border border-border bg-card/50 px-2 text-sm">{Object.keys(GRADE_POINTS).map(g=><option key={g}>{g}</option>)}</select><Input type="number" placeholder="Credits" value={c.credits} onChange={(e)=>upd(i,"credits",e.target.value)} /><Button variant="ghost" size="icon" onClick={()=>setCourses(c=>c.filter((_,idx)=>idx!==i))}><Trash2 className="size-4" /></Button></div>)}</div><Button variant="outline" size="sm" onClick={()=>setCourses(c=>[...c,{grade:"A",credits:"3"}])}><Plus className="size-4" />Add</Button><div className="glass rounded-lg p-5 text-center"><div className="text-3xl font-bold text-gradient-accent">{gpa.toFixed(2)}</div><div className="text-sm text-muted-foreground">GPA ({creds} credits)</div></div></div>);}
export function InflationCalculator(){const[a,setA]=useState("1000"),[r,setR]=useState("3"),[y,setY]=useState("10");const am=parseFloat(a),ra=parseFloat(r)/100,Y=parseFloat(y);const fut=am*Math.pow(1+ra,Y);return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="space-y-1.5"><Label>Amount</Label><Input type="number" value={a} onChange={(e)=>setA(e.target.value)} /></div><div className="space-y-1.5"><Label>Inflation %</Label><Input type="number" step="0.1" value={r} onChange={(e)=>setR(e.target.value)} /></div><div className="space-y-1.5"><Label>Years</Label><Input type="number" value={y} onChange={(e)=>setY(e.target.value)} /></div></div><div className="grid grid-cols-2 gap-3"><div className="glass rounded-lg p-4 text-center"><div className="text-xl font-semibold text-gradient-accent">{money(fut)}</div><div className="text-xs text-muted-foreground">In {Y} yrs</div></div><div className="glass rounded-lg p-4 text-center"><div className="text-xl font-semibold text-red-400">{money(fut-am)}</div><div className="text-xs text-muted-foreground">Power lost</div></div></div></div>);}
export function GasCostCalculator(){const[d,setD]=useState("300"),[m,setM]=useState("30"),[p,setP]=useState("3.5");const dist=parseFloat(d),mpg=parseFloat(m),pr=parseFloat(p);const g=mpg>0?dist/mpg:0;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="space-y-1.5"><Label>Distance (mi)</Label><Input type="number" value={d} onChange={(e)=>setD(e.target.value)} /></div><div className="space-y-1.5"><Label>MPG</Label><Input type="number" value={m} onChange={(e)=>setM(e.target.value)} /></div><div className="space-y-1.5"><Label>Price/gal</Label><Input type="number" step="0.01" value={p} onChange={(e)=>setP(e.target.value)} /></div></div><div className="grid grid-cols-2 gap-3"><div className="glass rounded-lg p-4 text-center"><div className="text-xl font-semibold text-gradient-accent">{g.toFixed(1)} gal</div><div className="text-xs text-muted-foreground">Fuel</div></div><div className="glass rounded-lg p-4 text-center"><div className="text-xl font-semibold text-gradient-accent">{money(g*pr)}</div><div className="text-xs text-muted-foreground">Cost</div></div></div></div>);}
export function RandomNumber(){const[min,setMin]=useState("1"),[max,setMax]=useState("100"),[count,setCount]=useState("1"),[unique,setUnique]=useState(false),[results,setResults]=useState<number[]>([]);function gen(){const lo=Math.ceil(parseFloat(min)||0),hi=Math.floor(parseFloat(max)||lo),n=Math.min(1000,Math.max(1,parseInt(count)||1));if(unique){const pool:number[]=[];for(let i=lo;i<=hi;i++)pool.push(i);pool.sort(()=>Math.random()-0.5);setResults(pool.slice(0,Math.min(n,pool.length)));}else setResults(Array.from({length:n},()=>Math.floor(Math.random()*(hi-lo+1))+lo));}return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="space-y-1.5"><Label>Min</Label><Input type="number" value={min} onChange={(e)=>setMin(e.target.value)} /></div><div className="space-y-1.5"><Label>Max</Label><Input type="number" value={max} onChange={(e)=>setMax(e.target.value)} /></div><div className="space-y-1.5"><Label>How many</Label><Input type="number" min={1} value={count} onChange={(e)=>setCount(e.target.value)} /></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-[hsl(var(--ring))]" checked={unique} onChange={(e)=>setUnique(e.target.checked)} /> Unique</label><Button variant="gradient" onClick={gen}><RefreshCw className="size-4" />Generate</Button><div className="flex flex-wrap gap-2">{results.map((r,i)=><span key={i} className="rounded-md border border-border bg-background/50 px-3 py-1.5 font-mono text-sm">{r}</span>)}</div></div>);}
export function CountdownTimer(){const[target,setTarget]=useState("");const[remaining,setRemaining]=useState<number|null>(null);useEffect(()=>{if(!target)return;const tick=()=>setRemaining(new Date(target).getTime()-Date.now());tick();const id=setInterval(tick,1000);return()=>clearInterval(id);},[target]);const fmt=(ms:number)=>{if(ms<=0)return"🎉 Time's up!";const d=Math.floor(ms/86400000),h=Math.floor(ms/3600000)%24,m=Math.floor(ms/60000)%60,s=Math.floor(ms/1000)%60;return`${d}d ${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;};return(<div className="space-y-4"><label className="block space-y-1.5 text-sm font-medium">Target<input type="datetime-local" value={target} onChange={(e)=>setTarget(e.target.value)} className="mt-1 block h-10 w-full rounded-md border border-border bg-card/50 px-3 text-sm" /></label><div className="glass rounded-lg p-8 text-center"><div className="text-3xl font-bold text-gradient-accent">{remaining==null?"Pick a target":fmt(remaining)}</div></div>{target&&<Button variant="outline" size="sm" onClick={()=>setTarget("")}>Reset</Button>}</div>);}
export function Stopwatch(){const[ms,setMs]=useState(0),[running,setRunning]=useState(false),[laps,setLaps]=useState<number[]>([]);const startRef=useRef(0);useEffect(()=>{if(!running)return;startRef.current=Date.now()-ms;const id=setInterval(()=>setMs(Date.now()-startRef.current),10);return()=>clearInterval(id);},[running]);const fmt=(x:number)=>`${String(Math.floor(x/60000)).padStart(2,"0")}:${String(Math.floor(x/1000)%60).padStart(2,"0")}.${String(Math.floor(x/10)%100).padStart(2,"0")}`;return(<div className="space-y-4"><div className="glass rounded-lg p-8 text-center"><div className="text-4xl font-bold font-mono text-gradient-accent">{fmt(ms)}</div></div><div className="flex justify-center gap-2"><Button variant="gradient" onClick={()=>setRunning(r=>!r)}>{running?"Pause":"Start"}</Button><Button variant="outline" onClick={()=>{if(running)setLaps(l=>[...l,ms]);}}>Lap</Button><Button variant="ghost" onClick={()=>{setMs(0);setLaps([]);setRunning(false);}}>Reset</Button></div>{laps.length>0&&<div className="max-h-40 space-y-1 overflow-auto">{laps.map((l,i)=><div key={i} className="flex justify-between rounded-md border border-border bg-background/50 px-3 py-1.5 font-mono text-sm"><span>Lap {i+1}</span><span>{fmt(l)}</span></div>)}</div>}</div>);}
const FIRST=["Alex","Sam","Jordan","Taylor","Morgan","Priya","Arjun","Mei","Omar","Zara"],LAST=["Smith","Khan","Patel","Garcia","Tanaka","Silva","Nguyen","Kim","Costa"],DOM=["example.com","mail.com","test.org"];function pick<T>(a:T[]):T{return a[Math.floor(Math.random()*a.length)];}
export function FakeDataGenerator(){const[count,setCount]=useState(5),[data,setData]=useState<any[]>([]);function gen(){setData(Array.from({length:count},()=>{const f=pick(FIRST),l=pick(LAST);return{name:`${f} ${l}`,email:`${f.toLowerCase()}.${l.toLowerCase()}@${pick(DOM)}`,phone:`+1-${Math.floor(200+Math.random()*800)}-${Math.floor(100+Math.random()*900)}-${Math.floor(1000+Math.random()*9000)}`,age:Math.floor(18+Math.random()*60)};}));}const csv=data.length?["name,email,phone,age",...data.map(d=>`${d.name},${d.email},${d.phone},${d.age}`)].join("\n"):"";return(<div className="space-y-4"><div className="flex items-center gap-3"><label className="text-sm text-muted-foreground">Rows</label><input type="number" min={1} max={100} value={count} onChange={(e)=>setCount(Math.min(100,Math.max(1,+e.target.value)))} className="h-9 w-20 rounded-md border border-border bg-card/50 px-2 text-sm" /><Button variant="gradient" onClick={gen}>Generate</Button>{csv&&<CopyButton value={csv} label="Copy CSV" />}</div>{data.length>0&&<div className="overflow-x-auto rounded-md border border-border"><table className="w-full text-left text-sm"><thead className="bg-card/50 text-xs uppercase text-muted-foreground"><tr>{["Name","Email","Phone","Age"].map(h=><th key={h} className="px-3 py-2">{h}</th>)}</tr></thead><tbody>{data.map((d,i)=><tr key={i} className="border-t border-border"><td className="px-3 py-2">{d.name}</td><td className="px-3 py-2 text-accent">{d.email}</td><td className="px-3 py-2 font-mono text-xs">{d.phone}</td><td className="px-3 py-2">{d.age}</td></tr>)}</tbody></table></div>}</div>);}
export function NetWorth(){const[a,setA]=useState("50000"),[l,setL]=useState("12000");const am=parseFloat(a)||0,li=parseFloat(l)||0;const nw=am-li;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Assets</Label><Input type="number" value={a} onChange={(e)=>setA(e.target.value)} /></div><div className="space-y-1.5"><Label>Liabilities</Label><Input type="number" value={l} onChange={(e)=>setL(e.target.value)} /></div></div><div className="glass rounded-lg p-6 text-center"><div className={`text-3xl font-bold ${nw>=0?"text-gradient-accent":"text-red-400"}`}>{money(nw)}</div><div className="text-sm text-muted-foreground">Net worth</div></div></div>);}
export function SavingsGoal(){const[g,setG]=useState("10000"),[c,setC]=useState("1000"),[m,setM]=useState("24"),[r,setR]=useState("4");const goal=parseFloat(g),cur=parseFloat(c),mo=parseFloat(m),ra=parseFloat(r)/100/12;const need=Math.max(0,goal-cur);const monthly=mo>0?(ra===0?need/mo:need*ra/(Math.pow(1+ra,mo)-1)):0;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Goal</Label><Input type="number" value={g} onChange={(e)=>setG(e.target.value)} /></div><div className="space-y-1.5"><Label>Saved</Label><Input type="number" value={c} onChange={(e)=>setC(e.target.value)} /></div><div className="space-y-1.5"><Label>Months</Label><Input type="number" value={m} onChange={(e)=>setM(e.target.value)} /></div><div className="space-y-1.5"><Label>Interest %</Label><Input type="number" step="0.1" value={r} onChange={(e)=>setR(e.target.value)} /></div></div><div className="glass rounded-lg p-6 text-center"><div className="text-3xl font-bold text-gradient-accent">{money(monthly)}</div><div className="text-sm text-muted-foreground">per month</div></div></div>);}
export function DebtPayoff({label="Balance"}:{label?:string}){const[b,setB]=useState("5000"),[r,setR]=useState("19.99"),[p,setP]=useState("200");const bal0=parseFloat(b),apr=parseFloat(r)/100/12,pay=parseFloat(p);let months=0,ti=0,bal=bal0;if(pay>bal0*apr&&bal0>0&&pay>0){while(bal>0&&months<600){const i=bal*apr;ti+=i;bal=bal+i-pay;months++;}}const fail=pay<=bal0*apr&&bal0>0;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="space-y-1.5"><Label>{label}</Label><Input type="number" value={b} onChange={(e)=>setB(e.target.value)} /></div><div className="space-y-1.5"><Label>APR %</Label><Input type="number" step="0.01" value={r} onChange={(e)=>setR(e.target.value)} /></div><div className="space-y-1.5"><Label>Monthly</Label><Input type="number" value={p} onChange={(e)=>setP(e.target.value)} /></div></div>{fail?<p className="rounded-md bg-amber-500/10 px-3 py-2 text-sm text-amber-400">Increase payment to cover interest.</p>:<div className="grid grid-cols-3 gap-3">{[["Time",`${Math.ceil(months/12)}y ${months%12}m`],["Interest",money(ti)],["Total",money(bal0+ti)]].map(([l,v])=><div key={l} className="glass rounded-lg p-3 text-center"><div className="text-base font-semibold text-gradient-accent">{v}</div><div className="text-xs text-muted-foreground">{l}</div></div>)}</div>}</div>);}
export function PayeTax({label="Gross income"}:{label?:string}){const[s,setS]=useState("60000"),[r,setR]=useState("20");const sal=parseFloat(s),ra=parseFloat(r)/100;const tax=sal*ra,net=sal-tax;return(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>{label}</Label><Input type="number" value={s} onChange={(e)=>setS(e.target.value)} /></div><div className="space-y-1.5"><Label>Tax %</Label><Input type="number" step="0.1" value={r} onChange={(e)=>setR(e.target.value)} /></div></div><div className="grid grid-cols-3 gap-3">{[["Tax",money(tax)],["Take-home",money(net)],["Monthly",money(net/12)]].map(([l,v])=><div key={l} className="glass rounded-lg p-3 text-center"><div className="text-base font-semibold text-gradient-accent">{v}</div><div className="text-xs text-muted-foreground">{l}</div></div>)}</div></div>);}
export function BarcodeGenerator(){const[text,setText]=useState("REXER12345");let url="";if(typeof document!=="undefined"){const c=document.createElement("canvas");c.width=600;c.height=200;const ctx=c.getContext("2d")!;ctx.fillStyle="#fff";ctx.fillRect(0,0,600,200);ctx.fillStyle="#000";let x=20;const seed=text||" ";for(let i=0;i<seed.length;i++){const code=seed.charCodeAt(i)+i*7;for(let b=0;b<4;b++){const w=((code>>b)&1)?3:1;if((code>>(b+4))&1)ctx.fillRect(x,20,w,120);x+=w+1;}x+=2;}ctx.font="20px monospace";ctx.textAlign="center";ctx.fillText(seed.toUpperCase(),300,170);url=c.toDataURL("image/png");}return(<div className="space-y-4"><div className="space-y-1.5"><Label>Data</Label><Input value={text} onChange={(e)=>setText(e.target.value)} /></div><div className="flex justify-center rounded-lg bg-white p-4">{/* eslint-disable-next-line @next/next/no-img-element */}{url&&<img src={url} alt="Barcode" className="max-h-44" />}</div>{url&&<a href={url} download="barcode.png" className="inline-flex w-full items-center justify-center gap-1.5 rounded-md bg-gradient-accent px-3 py-2 text-sm font-medium text-white">Download</a>}</div>);}
