import type { Tool } from "@/types/tools";

/**
 * FULL TOOLS REGISTRY — 200 tools.
 *
 * Categories & ID ranges (per project spec):
 *   media       1–47    Images / video / audio suite
 *   dev         48–74   Developers & UI/UX
 *   seo         75–79   SEO & Marketing
 *   docs        80–106  Documents & Utilities
 *   text        107–120 Text & Converters
 *   finance     121–150 Finance / Calculators / Productivity
 *   generators  151–160 Generators & Productivity
 *   ai          161–200 AI & Smart Tools
 *
 * Non-AI tools are 100% client-side (privacy-first). AI tools call cloud
 * APIs via env keys only; nothing is stored or logged.
 */
export const tools: Tool[] = [
  // ── Media & Creators (1–47) ──────────────────────────────────────────────
  { id: 1, slug: "tiktok-ig-reels-downloader", title: "TikTok & IG Reels Downloader", category: "media", short: "Fetch permitted videos from public URLs; respects platform TOS.", tags: ["video", "social", "downloader"] },
  { id: 2, slug: "youtube-shorts-downloader", title: "YouTube Shorts Downloader", category: "media", short: "Save public Shorts via user-provided links; TOS-aware.", tags: ["video", "social", "downloader"] },
  { id: 3, slug: "image-compressor", title: "Image Compressor", category: "media", short: "Shrink JPG/PNG/WebP file size in-browser, no uploads.", tags: ["image", "compress"] },
  { id: 4, slug: "image-resizer", title: "Image Resizer", category: "media", short: "Resize images to exact dimensions client-side with canvas.", tags: ["image", "resize"] },
  { id: 5, slug: "image-cropper", title: "Image Cropper", category: "media", short: "Crop images to any aspect ratio right in your browser.", tags: ["image", "crop"] },
  { id: 6, slug: "image-converter", title: "Image Converter", category: "media", short: "Convert WebP/HEIC/PNG/JPG between formats locally.", tags: ["image", "convert", "heic"] },
  { id: 7, slug: "image-rotator", title: "Image Rotator", category: "media", short: "Rotate or flip images by any angle, instantly.", tags: ["image", "rotate"] },
  { id: 8, slug: "image-to-base64", title: "Image to Base64", category: "media", short: "Encode any image to a Base64 data URI string.", tags: ["image", "base64"] },
  { id: 9, slug: "base64-to-image", title: "Base64 to Image", category: "media", short: "Decode a Base64 data URI back into a viewable image.", tags: ["image", "base64"] },
  { id: 10, slug: "color-picker-from-image", title: "Color Picker From Image", category: "media", short: "Pick exact pixel colors and copy HEX/RGB values.", tags: ["image", "color"] },
  { id: 11, slug: "photo-filters", title: "Photo Filters", category: "media", short: "Apply CSS/canvas filters: grayscale, sepia, contrast.", tags: ["image", "filters"] },
  { id: 12, slug: "image-watermark", title: "Image Watermark", category: "media", short: "Stamp text or logo watermarks onto images locally.", tags: ["image", "watermark"] },
  { id: 13, slug: "image-collage", title: "Image Collage Maker", category: "media", short: "Combine multiple photos into a grid collage.", tags: ["image", "collage"] },
  { id: 14, slug: "gif-maker", title: "GIF Maker", category: "media", short: "Turn a sequence of images into an animated GIF.", tags: ["image", "gif"] },
  { id: 15, slug: "gif-to-video", title: "GIF to Video", category: "media", short: "Convert animated GIFs to MP4/WebM (ffmpeg.wasm).", tags: ["video", "gif", "convert"] },
  { id: 16, slug: "video-to-gif", title: "Video to GIF", category: "media", short: "Create GIFs from video clips client-side.", tags: ["video", "gif"] },
  { id: 17, slug: "video-compressor", title: "Video Compressor", category: "media", short: "Reduce video size with ffmpeg.wasm — no uploads.", tags: ["video", "compress"] },
  { id: 18, slug: "video-trimmer", title: "Video Trimmer", category: "media", short: "Cut and trim video clips to the exact range you want.", tags: ["video", "trim"] },
  { id: 19, slug: "video-resizer", title: "Video Resizer", category: "media", short: "Resize or scale videos to target dimensions.", tags: ["video", "resize"] },
  { id: 20, slug: "video-converter", title: "Video Converter", category: "media", short: "Convert between MP4, WebM, MOV and more locally.", tags: ["video", "convert"] },
  { id: 21, slug: "audio-converter", title: "Audio Converter", category: "media", short: "Convert MP3, WAV, OGG, M4A in your browser.", tags: ["audio", "convert"] },
  { id: 22, slug: "audio-trimmer", title: "Audio Trimmer", category: "media", short: "Trim audio files to precise start/end points.", tags: ["audio", "trim"] },
  { id: 23, slug: "audio-compressor", title: "Audio Compressor", category: "media", short: "Reduce audio file size while keeping quality.", tags: ["audio", "compress"] },
  { id: 24, slug: "video-to-audio", title: "Video to Audio", category: "media", short: "Extract the audio track from any video file.", tags: ["video", "audio"] },
  { id: 25, slug: "audio-volume-booster", title: "Audio Volume Booster", category: "media", short: "Increase or normalize audio loudness locally.", tags: ["audio", "volume"] },
  { id: 26, slug: "video-mute", title: "Video Muter", category: "media", short: "Remove the audio track from a video instantly.", tags: ["video", "audio"] },
  { id: 27, slug: "screen-recorder", title: "Screen Recorder", category: "media", short: "Record your screen or a window with the Web APIs.", tags: ["video", "screen"] },
  { id: 28, slug: "frame-grabber", title: "Frame Grabber", category: "media", short: "Extract still frames from a video at any timestamp.", tags: ["video", "image"] },
  { id: 29, slug: "exif-viewer", title: "EXIF Metadata Viewer", category: "media", short: "Inspect photo EXIF, GPS and camera data locally.", tags: ["image", "metadata"] },
  { id: 30, slug: "exif-remover", title: "EXIF Remover", category: "media", short: "Strip metadata from photos for privacy.", tags: ["image", "privacy", "metadata"] },
  { id: 31, slug: "heic-to-jpg", title: "HEIC to JPG", category: "media", short: "Convert iPhone HEIC photos to JPG, no upload.", tags: ["image", "heic", "convert"] },
  { id: 32, slug: "webp-converter", title: "WebP Converter", category: "media", short: "Convert to/from modern WebP format locally.", tags: ["image", "webp", "convert"] },
  { id: 33, slug: "svg-to-png", title: "SVG to PNG", category: "media", short: "Rasterize SVG vectors to PNG at any scale.", tags: ["image", "svg"] },
  { id: 34, slug: "png-to-jpg", title: "PNG to JPG", category: "media", short: "Flatten transparency and convert PNG to JPG.", tags: ["image", "convert"] },
  { id: 35, slug: "image-flip", title: "Image Flipper", category: "media", short: "Mirror images horizontally or vertically.", tags: ["image", "edit"] },
  { id: 36, slug: "meme-generator", title: "Meme Generator", category: "media", short: "Add top/bottom captions to images classic-style.", tags: ["image", "fun"] },
  { id: 37, slug: "image-splitter", title: "Image Splitter", category: "media", short: "Slice an image into a grid of tiles.", tags: ["image", "split"] },
  { id: 38, slug: "image-combiner", title: "Image Combiner", category: "media", short: "Stitch images vertically or horizontally.", tags: ["image", "merge"] },
  { id: 39, slug: "audio-normalizer", title: "Audio Normalizer", category: "media", short: "Normalize audio peak levels for consistent volume.", tags: ["audio", "edit"] },
  { id: 40, slug: "video-thumbnail", title: "Video Thumbnail Maker", category: "media", short: "Grab poster thumbnails from a video.", tags: ["video", "image"] },
  { id: 41, slug: "image-round-corners", title: "Round Image Corners", category: "media", short: "Add rounded corners or circle masks to images.", tags: ["image", "edit"] },
  { id: 42, slug: "image-background-color", title: "Image Background Color", category: "media", short: "Set or replace a solid background color.", tags: ["image", "edit"] },
  { id: 43, slug: "image-metadata-editor", title: "Image Metadata Editor", category: "media", short: "Edit basic EXIF/IPTC fields on your photos.", tags: ["image", "metadata"] },
  { id: 44, slug: "audio-reverse", title: "Audio Reverser", category: "media", short: "Play audio backwards — fully client-side.", tags: ["audio", "fun"] },
  { id: 45, slug: "video-speed", title: "Video Speed Changer", category: "media", short: "Speed up or slow down video playback.", tags: ["video", "edit"] },
  { id: 46, slug: "image-grayscale", title: "Image to Grayscale", category: "media", short: "Convert color photos to black & white instantly.", tags: ["image", "filters"] },
  { id: 47, slug: "image-text-overlay", title: "Image Text Overlay", category: "media", short: "Add styled text over images with full control.", tags: ["image", "text"] },

  // ── Developers & UI/UX (48–74) ───────────────────────────────────────────
  { id: 48, slug: "json-formatter", title: "JSON Formatter", category: "dev", short: "Beautify, minify and validate JSON in your browser.", tags: ["json", "formatter"] },
  { id: 49, slug: "json-validator", title: "JSON Validator", category: "dev", short: "Check JSON syntax and pinpoint errors instantly.", tags: ["json", "validate"] },
  { id: 50, slug: "json-to-csv", title: "JSON to CSV", category: "dev", short: "Flatten JSON arrays into CSV spreadsheets.", tags: ["json", "csv"] },
  { id: 51, slug: "csv-to-json", title: "CSV to JSON", category: "dev", short: "Parse CSV data into clean JSON objects.", tags: ["csv", "json"] },
  { id: 52, slug: "base64-encode-decode", title: "Base64 Encode / Decode", category: "dev", short: "Encode or decode text and bytes to Base64.", tags: ["base64", "encode"] },
  { id: 53, slug: "url-encode-decode", title: "URL Encode / Decode", category: "dev", short: "Percent-encode or decode URLs and query strings.", tags: ["url", "encode"] },
  { id: 54, slug: "html-entity-encoder", title: "HTML Entity Encoder", category: "dev", short: "Escape or unescape HTML entities safely.", tags: ["html", "encode"] },
  { id: 55, slug: "css-minifier", title: "CSS Minifier", category: "dev", short: "Minify CSS to reduce stylesheet size.", tags: ["css", "minify"] },
  { id: 56, slug: "js-minifier", title: "JS Minifier", category: "dev", short: "Compress JavaScript while keeping it valid.", tags: ["javascript", "minify"] },
  { id: 57, slug: "js-beautifier", title: "JS Beautifier", category: "dev", short: "Pretty-print and indent messy JavaScript.", tags: ["javascript", "format"] },
  { id: 58, slug: "html-formatter", title: "HTML Formatter", category: "dev", short: "Beautify and indent HTML markup.", tags: ["html", "format"] },
  { id: 59, slug: "css-beautifier", title: "CSS Beautifier", category: "dev", short: "Pretty-print CSS rules with consistent style.", tags: ["css", "format"] },
  { id: 60, slug: "json-minifier", title: "JSON Minifier", category: "dev", short: "Strip whitespace from JSON for smaller payloads.", tags: ["json", "minify"] },
  { id: 61, slug: "regex-tester", title: "Regex Tester", category: "dev", short: "Test regular expressions with live match highlights.", tags: ["regex", "test"] },
  { id: 62, slug: "uuid-generator", title: "UUID Generator", category: "dev", short: "Generate RFC-4122 v4 UUIDs in bulk.", tags: ["uuid", "generator"] },
  { id: 63, slug: "hash-generator", title: "Hash Generator", category: "dev", short: "Compute MD5, SHA-1, SHA-256 hashes via WebCrypto.", tags: ["hash", "crypto"] },
  { id: 64, slug: "jwt-decoder", title: "JWT Decoder", category: "dev", short: "Decode and inspect JSON Web Token payloads.", tags: ["jwt", "decode"] },
  { id: 65, slug: "diff-checker", title: "Diff Checker", category: "dev", short: "Compare two text blocks line-by-line.", tags: ["diff", "text"] },
  { id: 66, slug: "cron-builder", title: "Cron Expression Builder", category: "dev", short: "Build and explain cron schedules visually.", tags: ["cron", "schedule"] },
  { id: 67, slug: "token-counter", title: "Token Counter", category: "dev", short: "Estimate LLM token counts for prompts and text.", tags: ["tokens", "ai"] },
  { id: 68, slug: "curl-to-code", title: "cURL to Code", category: "dev", short: "Convert cURL commands to JS, Python, Go fetch code.", tags: ["curl", "codegen"] },
  { id: 69, slug: "json-to-typescript", title: "JSON to TypeScript", category: "dev", short: "Generate TS interfaces from any JSON object.", tags: ["json", "typescript"] },
  { id: 70, slug: "json-to-zod", title: "JSON to Zod / Pydantic", category: "dev", short: "Generate Zod or Pydantic schemas from JSON.", tags: ["json", "schema"] },
  { id: 71, slug: "jsonl-viewer", title: "JSONL Viewer", category: "dev", short: "Browse and search newline-delimited JSON logs.", tags: ["json", "logs"] },
  { id: 72, slug: "json-schema-builder", title: "JSON Schema Builder", category: "dev", short: "Visually build JSON Schema documents.", tags: ["json", "schema"] },
  { id: 73, slug: "chat-export-converter", title: "Chat Export Converter", category: "dev", short: "Convert chat exports between common formats.", tags: ["chat", "convert"] },
  { id: 74, slug: "color-converter", title: "Color Converter", category: "dev", short: "Convert HEX, RGB, HSL colors and build palettes.", tags: ["color", "convert"] },

  // ── SEO & Marketing (75–79) ──────────────────────────────────────────────
  { id: 75, slug: "meta-og-generator", title: "Meta & OG Tag Generator", category: "seo", short: "Generate SEO meta and Open Graph tags for any page.", tags: ["seo", "meta", "og"] },
  { id: 76, slug: "social-preview-checker", title: "Social Preview Checker", category: "seo", short: "Preview how your link looks when shared.", tags: ["seo", "social"] },
  { id: 77, slug: "keyword-density", title: "Keyword Density Analyzer", category: "seo", short: "Analyze keyword frequency and SEO density.", tags: ["seo", "keywords"] },
  { id: 78, slug: "robots-txt-generator", title: "Robots.txt Generator", category: "seo", short: "Build a robots.txt with rules per crawler.", tags: ["seo", "robots"] },
  { id: 79, slug: "sitemap-generator", title: "Sitemap.xml Generator", category: "seo", short: "Create XML sitemaps from a list of URLs.", tags: ["seo", "sitemap"] },

  // ── Documents & Utilities (80–106) ───────────────────────────────────────
  { id: 80, slug: "pdf-to-word", title: "PDF to Word", category: "docs", short: "Extract PDF text into an editable document.", tags: ["pdf", "word"] },
  { id: 81, slug: "word-to-pdf", title: "Word to PDF", category: "docs", short: "Render document text to a clean PDF.", tags: ["pdf", "word"] },
  { id: 82, slug: "cv-builder", title: "CV / Resume Builder", category: "docs", short: "Build a clean, printable resume in minutes.", tags: ["resume", "cv"] },
  { id: 83, slug: "pdf-merge", title: "PDF Merge", category: "docs", short: "Combine multiple PDFs into one with pdf-lib.", tags: ["pdf", "merge"] },
  { id: 84, slug: "pdf-split", title: "PDF Split", category: "docs", short: "Split a PDF into individual pages or ranges.", tags: ["pdf", "split"] },
  { id: 85, slug: "pdf-compress", title: "PDF Compress", category: "docs", short: "Reduce PDF file size client-side.", tags: ["pdf", "compress"] },
  { id: 86, slug: "pdf-extract-text", title: "PDF Text Extractor", category: "docs", short: "Pull selectable text out of a PDF locally.", tags: ["pdf", "text"] },
  { id: 87, slug: "pdf-sign", title: "PDF Sign", category: "docs", short: "Draw or place a signature onto a PDF.", tags: ["pdf", "sign"] },
  { id: 88, slug: "pdf-form-filler", title: "PDF Form Filler", category: "docs", short: "Fill interactive PDF form fields in-browser.", tags: ["pdf", "forms"] },
  { id: 89, slug: "pdf-watermark", title: "PDF Watermark", category: "docs", short: "Stamp text or image watermarks onto PDFs.", tags: ["pdf", "watermark"] },
  { id: 90, slug: "pdf-unlock", title: "PDF Unlock", category: "docs", short: "Remove a known password from a PDF you own.", tags: ["pdf", "password"] },
  { id: 91, slug: "pdf-header-footer", title: "PDF Header & Footer", category: "docs", short: "Add page headers and footers to a PDF.", tags: ["pdf", "edit"] },
  { id: 92, slug: "pdf-resize", title: "PDF Page Resizer", category: "docs", short: "Scale or change PDF page dimensions.", tags: ["pdf", "resize"] },
  { id: 93, slug: "invoice-generator", title: "Invoice Generator", category: "docs", short: "Create and print professional PDF invoices.", tags: ["invoice", "pdf"] },
  { id: 94, slug: "whatsapp-dm-generator", title: "WhatsApp DM Generator", category: "docs", short: "Build prefilled WhatsApp messages and links.", tags: ["whatsapp", "link"] },
  { id: 95, slug: "word-counter", title: "Word Counter", category: "docs", short: "Count words, characters, sentences and read time.", tags: ["text", "count"] },
  { id: 96, slug: "case-converter", title: "Case Converter", category: "docs", short: "Switch between UPPER, lower, Title and more.", tags: ["text", "case"] },
  { id: 97, slug: "remove-duplicate-lines", title: "Remove Duplicate Lines", category: "docs", short: "Deduplicate lines and keep order.", tags: ["text", "dedupe"] },
  { id: 98, slug: "sort-lines", title: "Sort Lines", category: "docs", short: "Alphabetically sort lines ascending or descending.", tags: ["text", "sort"] },
  { id: 99, slug: "find-and-replace", title: "Find & Replace", category: "docs", short: "Replace text with optional regex support.", tags: ["text", "replace"] },
  { id: 100, slug: "text-diff", title: "Text Diff Checker", category: "docs", short: "Compare two texts and highlight changes.", tags: ["text", "diff"] },
  { id: 101, slug: "trim-whitespace", title: "Trim & Clean Whitespace", category: "docs", short: "Trim spaces, tabs and blank lines from text.", tags: ["text", "clean"] },
  { id: 102, slug: "markdown-to-html", title: "Markdown to HTML", category: "docs", short: "Convert Markdown into clean HTML.", tags: ["markdown", "html"] },
  { id: 103, slug: "notepad", title: "Online Notepad", category: "docs", short: "A private autosaving scratchpad in your browser.", tags: ["notes", "editor"] },
  { id: 104, slug: "password-generator", title: "Secure Password Generator", category: "generators", short: "Generate strong passwords with a live strength meter.", tags: ["password", "security", "generator"] },
  { id: 105, slug: "extract-emails-urls", title: "Extract Emails & URLs", category: "docs", short: "Pull emails and links out of any block of text.", tags: ["text", "extract"] },
  { id: 106, slug: "remove-line-breaks", title: "Remove Line Breaks", category: "docs", short: "Strip or replace line breaks in text.", tags: ["text", "clean"] },

  // ── Text & Converters (107–120) ──────────────────────────────────────────
  { id: 107, slug: "emoji-picker", title: "Emoji Picker", category: "text", short: "Browse and copy thousands of emojis instantly.", tags: ["emoji", "copy"] },
  { id: 108, slug: "fancy-text", title: "Fancy Text Generator", category: "text", short: "Style text with Unicode fonts for bios.", tags: ["text", "style"] },
  { id: 109, slug: "handwriting-text", title: "Handwriting Text", category: "text", short: "Render text in handwriting-style fonts.", tags: ["text", "font"] },
  { id: 110, slug: "unit-converter", title: "Unit Converter", category: "text", short: "Convert length, weight, temperature and more.", tags: ["units", "convert"] },
  { id: 111, slug: "currency-converter", title: "Currency Converter", category: "text", short: "Convert between currencies with live rates.", tags: ["currency", "convert"] },
  { id: 112, slug: "timezone-converter", title: "Timezone Converter", category: "text", short: "Compare times across world timezones.", tags: ["time", "timezone"] },
  { id: 113, slug: "base-converter", title: "Base (Radix) Converter", category: "text", short: "Convert numbers between binary, hex, decimal.", tags: ["numbers", "convert"] },
  { id: 114, slug: "csv-json-converter", title: "CSV ↔ JSON Converter", category: "text", short: "Convert between CSV and JSON either direction.", tags: ["csv", "json"] },
  { id: 115, slug: "number-formatter", title: "Number Formatter", category: "text", short: "Format numbers with thousands separators.", tags: ["numbers", "format"] },
  { id: 116, slug: "url-slug-generator", title: "URL Slug Generator", category: "text", short: "Make SEO-friendly slugs from any title.", tags: ["url", "slug"] },
  { id: 117, slug: "text-encoder-decoder", title: "Text Encoder / Decoder", category: "text", short: "Encode/decode Base64, hex, URL and more.", tags: ["text", "encode"] },
  { id: 118, slug: "lorem-ipsum", title: "Lorem Ipsum Generator", category: "text", short: "Generate placeholder text by paragraphs.", tags: ["text", "placeholder"] },
  { id: 119, slug: "random-text", title: "Random Text Generator", category: "text", short: "Create random words, sentences and paragraphs.", tags: ["text", "random"] },
  { id: 120, slug: "text-reverser", title: "Text Reverser", category: "text", short: "Reverse characters, words or lines of text.", tags: ["text", "fun"] },

  // ── Finance / Calculators / Productivity (121–150) ───────────────────────
  { id: 121, slug: "bookkeeping", title: "Bookkeeping", category: "finance", short: "Track income and expenses simply and privately.", tags: ["finance", "ledger"] },
  { id: 122, slug: "money-manager", title: "Money Manager", category: "finance", short: "Budget and categorize spending in your browser.", tags: ["finance", "budget"] },
  { id: 123, slug: "compound-interest", title: "Compound Interest", category: "finance", short: "Calculate compound growth over time.", tags: ["finance", "calc"] },
  { id: 124, slug: "savings-goal", title: "Savings Goal Planner", category: "finance", short: "Plan how long to reach a savings target.", tags: ["finance", "savings"] },
  { id: 125, slug: "net-worth", title: "Net Worth Tracker", category: "finance", short: "Sum your assets minus liabilities privately.", tags: ["finance", "tracker"] },
  { id: 126, slug: "debt-payoff", title: "Debt Payoff Calculator", category: "finance", short: "Plan debt payoff with snowball or avalanche.", tags: ["finance", "debt"] },
  { id: 127, slug: "paye-tax", title: "PAYE / Tax Calculator", category: "finance", short: "Estimate take-home pay after income tax.", tags: ["finance", "tax"] },
  { id: 128, slug: "paycheck-calculator", title: "Paycheck Calculator", category: "finance", short: "Estimate net pay per period.", tags: ["finance", "calc"] },
  { id: 129, slug: "credit-card-payoff", title: "Credit Card Payoff", category: "finance", short: "See how fast you can clear card balances.", tags: ["finance", "debt"] },
  { id: 130, slug: "mortgage-calculator", title: "Mortgage Calculator", category: "finance", short: "Compute monthly payments and total interest.", tags: ["finance", "loan"] },
  { id: 131, slug: "tip-calculator", title: "Tip Calculator", category: "finance", short: "Split bills and tips across a group.", tags: ["finance", "calc"] },
  { id: 132, slug: "sales-tax", title: "Sales Tax Calculator", category: "finance", short: "Add or remove sales tax from any amount.", tags: ["finance", "tax"] },
  { id: 133, slug: "percentage-calculator", title: "Percentage Calculator", category: "finance", short: "Work out percentages, increase and change.", tags: ["math", "percent"] },
  { id: 134, slug: "loan-calculator", title: "Loan Calculator", category: "finance", short: "Estimate installments for any loan.", tags: ["finance", "loan"] },
  { id: 135, slug: "age-calculator", title: "Age Calculator", category: "finance", short: "Calculate exact age in years, months, days.", tags: ["date", "calc"] },
  { id: 136, slug: "bmi-calculator", title: "BMI Calculator", category: "finance", short: "Compute Body Mass Index and category.", tags: ["health", "calc"] },
  { id: 137, slug: "date-difference", title: "Date Difference", category: "finance", short: "Count days, weeks and months between dates.", tags: ["date", "calc"] },
  { id: 138, slug: "countdown-timer", title: "Countdown Timer", category: "finance", short: "Count down to any future date and time.", tags: ["time", "countdown"] },
  { id: 139, slug: "stopwatch", title: "Stopwatch", category: "finance", short: "A precise stopwatch with lap times.", tags: ["time", "stopwatch"] },
  { id: 140, slug: "bill-splitter", title: "Bill Splitter", category: "finance", short: "Split a bill evenly across any number of people.", tags: ["finance", "split"] },
  { id: 141, slug: "discount-calculator", title: "Discount Calculator", category: "finance", short: "Find the final price after discounts.", tags: ["finance", "calc"] },
  { id: 142, slug: "gpa-calculator", title: "GPA Calculator", category: "finance", short: "Compute grade point average per semester.", tags: ["school", "calc"] },
  { id: 143, slug: "car-loan-calculator", title: "Car Loan Calculator", category: "finance", short: "Estimate auto loan payments and interest.", tags: ["finance", "loan"] },
  { id: 144, slug: "grade-calculator", title: "Grade Calculator", category: "finance", short: "Calculate weighted grades and finals needed.", tags: ["school", "calc"] },
  { id: 145, slug: "inflation-calculator", title: "Inflation Calculator", category: "finance", short: "See how purchasing power changes over time.", tags: ["finance", "calc"] },
  { id: 146, slug: "gas-cost-calculator", title: "Gas Cost Calculator", category: "finance", short: "Estimate fuel cost for a trip.", tags: ["finance", "calc"] },
  { id: 147, slug: "rent-vs-buy", title: "Rent vs Buy Calculator", category: "finance", short: "Compare renting and buying over time.", tags: ["finance", "calc"] },
  { id: 148, slug: "barcode-generator", title: "Barcode Generator", category: "finance", short: "Create CODE128/EAN barcodes as images.", tags: ["barcode", "generator"] },
  { id: 149, slug: "random-number", title: "Random Number Generator", category: "finance", short: "Pick random numbers in any range.", tags: ["random", "numbers"] },
  { id: 150, slug: "fake-data-generator", title: "Fake Data Generator", category: "finance", short: "Generate mock names, emails and addresses.", tags: ["data", "mock"] },

  // ── Generators & Productivity (151–160) ──────────────────────────────────
  { id: 151, slug: "qr-code-generator", title: "QR Code Generator", category: "generators", short: "Create scannable QR codes for links and text.", tags: ["qr", "generator"] },
  { id: 152, slug: "qr-code-scanner", title: "QR Code Scanner", category: "generators", short: "Scan QR codes with your device camera.", tags: ["qr", "scanner"] },
  { id: 153, slug: "username-generator", title: "Username Generator", category: "generators", short: "Create unique, available-sounding usernames.", tags: ["username", "generator"] },
  { id: 154, slug: "business-name-generator", title: "Business Name Generator", category: "generators", short: "Brainstorm brand and business name ideas.", tags: ["name", "generator"] },
  { id: 155, slug: "random-name-picker", title: "Random Name Picker", category: "generators", short: "Pick a random winner from a list of names.", tags: ["random", "picker"] },
  { id: 156, slug: "coin-flip", title: "Coin Flip", category: "generators", short: "Flip a virtual coin for quick decisions.", tags: ["random", "fun"] },
  { id: 157, slug: "spin-wheel", title: "Spin Wheel", category: "generators", short: "Spin a custom wheel to pick options randomly.", tags: ["random", "fun"] },
  { id: 158, slug: "to-do-list", title: "To-Do List", category: "generators", short: "A private, autosaving to-do list.", tags: ["productivity", "todo"] },
  { id: 159, slug: "habit-tracker", title: "Habit Tracker", category: "generators", short: "Track daily habits and streaks locally.", tags: ["productivity", "habit"] },
  { id: 160, slug: "typing-test", title: "Typing Speed Test", category: "generators", short: "Measure your words-per-minute typing speed.", tags: ["typing", "test"] },

  // ── AI & Smart Tools (161–200) ───────────────────────────────────────────
  { id: 161, slug: "ai-text-rewriter", title: "AI Text Rewriter", category: "ai", short: "Rewrite text with cloud AI; nothing is stored.", tags: ["ai", "writing"] },
  { id: 162, slug: "ai-paraphraser", title: "AI Paraphraser", category: "ai", short: "Rephrase sentences while keeping meaning.", tags: ["ai", "writing"] },
  { id: 163, slug: "ai-grammar-checker", title: "AI Grammar Checker", category: "ai", short: "Fix grammar and spelling with AI assistance.", tags: ["ai", "writing"] },
  { id: 164, slug: "ai-blog-writer", title: "AI Blog Writer", category: "ai", short: "Draft full blog posts from a topic.", tags: ["ai", "writing"] },
  { id: 165, slug: "ai-caption-generator", title: "AI Caption Generator", category: "ai", short: "Generate social captions in your brand voice.", tags: ["ai", "social"] },
  { id: 166, slug: "ai-email-writer", title: "AI Email Writer", category: "ai", short: "Compose professional emails from bullet points.", tags: ["ai", "writing"] },
  { id: 167, slug: "ai-resume-writer", title: "AI Resume Writer", category: "ai", short: "Polish and optimize your resume content.", tags: ["ai", "resume"] },
  { id: 168, slug: "ai-headline-generator", title: "AI Headline Generator", category: "ai", short: "Craft catchy headlines and titles.", tags: ["ai", "writing"] },
  { id: 169, slug: "ai-product-description", title: "AI Product Description", category: "ai", short: "Write product copy that sells.", tags: ["ai", "marketing"] },
  { id: 170, slug: "ai-tweet-generator", title: "AI Tweet Generator", category: "ai", short: "Draft tweets and threads on any topic.", tags: ["ai", "social"] },
  { id: 171, slug: "ai-image-generator", title: "AI Image Generator", category: "ai", short: "Generate images from text prompts via cloud AI.", tags: ["ai", "image"] },
  { id: 172, slug: "ai-background-remover", title: "AI Background Remover", category: "ai", short: "Remove image backgrounds with AI precision.", tags: ["ai", "image"] },
  { id: 173, slug: "ai-image-enhancer", title: "AI Image Enhancer", category: "ai", short: "Upscale and sharpen photos with AI.", tags: ["ai", "image"] },
  { id: 174, slug: "ai-retouch", title: "AI Photo Retouch", category: "ai", short: "Retouch portraits and remove blemishes.", tags: ["ai", "image"] },
  { id: 175, slug: "ai-logo-generator", title: "AI Logo Generator", category: "ai", short: "Generate logo concepts from a brand name.", tags: ["ai", "design"] },
  { id: 176, slug: "ai-thumbnail-generator", title: "AI Thumbnail Generator", category: "ai", short: "Create eye-catching video thumbnails.", tags: ["ai", "design"] },
  { id: 177, slug: "ai-colorize", title: "AI Photo Colorize", category: "ai", short: "Colorize black-and-white photos with AI.", tags: ["ai", "image"] },
  { id: 178, slug: "ai-object-remover", title: "AI Object Remover", category: "ai", short: "Erase unwanted objects from photos.", tags: ["ai", "image"] },
  { id: 179, slug: "ai-sketch-to-image", title: "AI Sketch to Image", category: "ai", short: "Turn rough sketches into finished images.", tags: ["ai", "image"] },
  { id: 180, slug: "ai-profile-pic", title: "AI Profile Pic", category: "ai", short: "Generate stylized profile pictures.", tags: ["ai", "image"] },
  { id: 181, slug: "ai-video-generator", title: "AI Video Generator", category: "ai", short: "Create short videos from text prompts.", tags: ["ai", "video"] },
  { id: 182, slug: "ai-subtitle-generator", title: "AI Subtitle Generator", category: "ai", short: "Auto-generate captions for video/audio.", tags: ["ai", "video"] },
  { id: 183, slug: "ai-voice-generator", title: "AI Voice Generator", category: "ai", short: "Turn text into natural speech (TTS).", tags: ["ai", "audio"] },
  { id: 184, slug: "ai-voice-clone", title: "AI Voice Clone", category: "ai", short: "Clone a voice sample (confirmation required).", tags: ["ai", "audio"] },
  { id: 185, slug: "ai-noise-removal", title: "AI Noise Removal", category: "ai", short: "Clean background noise from audio.", tags: ["ai", "audio"] },
  { id: 186, slug: "ai-podcast-editor", title: "AI Podcast Editor", category: "ai", short: "Edit and clean up podcast audio.", tags: ["ai", "audio"] },
  { id: 187, slug: "ai-video-summarizer", title: "AI Video Summarizer", category: "ai", short: "Summarize long videos into key points.", tags: ["ai", "video"] },
  { id: 188, slug: "ai-speech-to-text", title: "AI Speech to Text", category: "ai", short: "Transcribe audio to text with Whisper.", tags: ["ai", "transcribe"] },
  { id: 189, slug: "ai-translator", title: "AI Translator", category: "ai", short: "Translate text across many languages.", tags: ["ai", "translate"] },
  { id: 190, slug: "ai-lip-sync", title: "AI Lip Sync", category: "ai", short: "Sync audio to video lips (confirmation required).", tags: ["ai", "video"] },
  { id: 191, slug: "ai-code-generator", title: "AI Code Generator", category: "ai", short: "Generate code snippets from a description.", tags: ["ai", "code"] },
  { id: 192, slug: "ai-debugger", title: "AI Debugger", category: "ai", short: "Explain and fix bugs in your code.", tags: ["ai", "code"] },
  { id: 193, slug: "ai-regex-generator", title: "AI Regex Generator", category: "ai", short: "Describe a match, get a working regex.", tags: ["ai", "regex"] },
  { id: 194, slug: "ai-sql-generator", title: "AI SQL Generator", category: "ai", short: "Turn plain English into SQL queries.", tags: ["ai", "sql"] },
  { id: 195, slug: "ai-json-fixer", title: "AI JSON Fixer", category: "ai", short: "Repair broken JSON automatically.", tags: ["ai", "json"] },
  { id: 196, slug: "ai-mock-api", title: "AI Mock API Generator", category: "ai", short: "Generate mock API responses and data.", tags: ["ai", "api"] },
  { id: 197, slug: "ai-chatbot-builder", title: "AI Chatbot Builder", category: "ai", short: "Build a custom chatbot from your content.", tags: ["ai", "chat"] },
  { id: 198, slug: "ai-prompt-generator", title: "AI Prompt Generator", category: "ai", short: "Craft better prompts for any AI model.", tags: ["ai", "prompt"] },
  { id: 199, slug: "ai-document-summarizer", title: "AI Document Summarizer", category: "ai", short: "Summarize long documents into key points.", tags: ["ai", "summary"] },
  { id: 200, slug: "ai-pdf-chat", title: "AI PDF Chat", category: "ai", short: "Ask questions about a PDF, ephemeral only.", tags: ["ai", "pdf"] },
];

/** Look up a single tool by its slug. */
export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

/** All unique categories that currently have at least one tool. */
export function getActiveCategories(): Tool["category"][] {
  return Array.from(new Set(tools.map((t) => t.category)));
}
